### ISSUE TITLE
2.079最新版本下是没有不带疾跑的地图数据了吗？ 尝试关闭疾跑，但是直接报错

### ISSUE THREAD

**Issue by fateholder** [linruowuyin/Fhoe-Rail#146]
我记得我昨天更新前好像还是不带疾跑的，今天变成带疾跑的了，之前用疾跑在坐电梯的时候总是有点问题

**Comment by smjes3** [comment]
理论上最新版本坐电梯用疾跑应该不会有问题，如果有问题的话你发日志我们看一下。

如果要不用疾跑的话，在config.json里面将auto_run_in_map改为False。

**Comment by smjes3** [comment]
你是如何尝试关闭疾跑的，报错是什么内容也可以发一下我们看看。

**Comment by fateholder** [comment]
之前好像配置里可以选是否疾跑，我就没改config,今天是改了config里的"auto_run_in_map":false,   但会直接报错

2024-03-18 13:12:36,586 | INFO | 开始锄大地
Traceback (most recent call last):
  File "Honkai_Star_Rail.py", line 275, in <module>
  File "Honkai_Star_Rail.py", line 96, in main
  File "utils\map.py", line 19, in __init__
  File "utils\config.py", line 71, in read_json_file
orjson.JSONDecodeError: byte order mark (BOM) is not supported: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Honkai_Star_Rail.py", line 283, in <module>
  File "loguru\_logger.py", line 2056, in error
  File "loguru\_logger.py", line 2029, in _log
  File "utils\log.py", line 40, in update_extra
  File "utils\log.py", line 26, in get_ver
  File "utils\config.py", line 24, in CONFIG
  File "utils\config.py", line 28, in _update_config
  File "utils\config.py", line 71, in read_json_file
orjson.JSONDecodeError: byte order mark (BOM) is not supported: line 1 column 1 (char 0)
[76284] Failed to execute script 'Honkai_Star_Rail' due to unhandled exception!
2024-03-18 13:12:37,939 | ERROR | 锄大地失败
2024-03-18 13:12:37,941 | INFO | ⚠️锄大地未完成⚠️
2024-03-18 13:12:39,329 | INFO | winotify 通知发送完成

**Comment by smjes3** [comment]
报错说明是编码问题。方便告知是使用什么编辑器修改的config.json么。
这个我们这里也可以做兼容处理，晚些会尝试将报错编码识别并自动移除避免报错。

**Comment by smjes3** [comment]
我们现在并不建议使用非疾跑，所以将疾跑开关隐藏了起来，如果有疾跑问题可以提出，我们会尽快修复。
可以尝试一下电梯问题，前几个版本已经修复了。

**Comment by fateholder** [comment]
确实是编码变了，默认是GB的，我用EmEditor编辑后变成utf-8了。
电梯现在没问题了，我再用用看。
