### ISSUE TITLE
[Bug] 卡在地图来回拖动，无法正常锄大地

### ISSUE THREAD

**Issue by niuhuan** [linruowuyin/Fhoe-Rail#260]
### 问题描述

电脑在挂机，手机打开游戏，切号的时候不小心把电脑顶掉了，电脑点击重新登录，会把怪重新打完，当前小地图的怪清完后。锄大地工具会打开地图进行传送，可能是因为地图缩放比例不一样或者地图偏移不一样，然后就一直在地图界面拖来拖去，再也不听话了。

### 预期行为

我希望能继续锄大地

### 实际行为

重启游戏和锄大地比较麻烦，我遇到了问题，但是没有解决方案的思路。或者像flutterDebug模式下的监听命令行的输入，对线路进行更正？

### 自动锄大地脚本版本

最新版

### 日志

日志应该并无参考价值
```
08:42:26 - INFO   	| calculated.click:136                     	- 2.1.18 - 点击坐标(959, 539)
08:42:27 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:4/13 {'fighting': 1}
08:42:27 - INFO   	| calculated.detect_fight_status:473       	- 2.1.18 - 开始识别是否进入战斗
08:42:28 - INFO   	| calculated.no_in_fight_status:462        	- 2.1.18 - 未战斗识别，匹配度0.849，需要0.95
08:42:28 - INFO   	| calculated.fight_elapsed:529             	- 2.1.18 - 战斗开始
08:42:50 - INFO   	| calculated.fight_elapsed:541             	- 2.1.18 - 识别点位(241, 81)
08:42:50 - INFO   	| calculated.fight_elapsed:549             	- 2.1.18 - 战斗完成,单场用时[1;92m『0分钟22.37秒』[0m
08:42:50 - INFO   	| calculated.fight_elapsed:551             	- 2.1.18 - 匹配度: 0.95 (241, 81)
08:42:50 - INFO   	| calculated.on_interface:1225             	- 2.1.18 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
08:42:50 - INFO   	| calculated.on_interface:1226             	- 2.1.18 - 检测图片序号为0，匹配度0.950，匹配位置为(233, 64)
08:42:51 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:5/13 {'d': 1.5}
08:42:52 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:6/13 {'s': 3}
08:42:55 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:7/13 {'a': 0.69}
08:42:56 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:8/13 {'s': 4.2}
08:42:59 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:9/13 {'a': 1.3}
08:43:00 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:10/13 {'s': 4.0}
08:43:03 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:11/13 {'a': 2.0}
08:43:05 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:12/13 {'s': 0.3}
08:43:05 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-6_7文件:13/13 {'fighting': 1}
08:43:06 - INFO   	| calculated.detect_fight_status:473       	- 2.1.18 - 开始识别是否进入战斗
08:43:06 - INFO   	| calculated.no_in_fight_status:462        	- 2.1.18 - 未战斗识别，匹配度0.880，需要0.95
08:43:06 - INFO   	| calculated.fight_elapsed:529             	- 2.1.18 - 战斗开始
08:43:42 - INFO   	| calculated.fight_elapsed:541             	- 2.1.18 - 识别点位(241, 81)
08:43:42 - INFO   	| calculated.fight_elapsed:549             	- 2.1.18 - 战斗完成,单场用时[1;92m『0分钟36.09秒』[0m
08:43:42 - INFO   	| calculated.fight_elapsed:551             	- 2.1.18 - 匹配度: 0.99 (241, 81)
08:43:42 - INFO   	| calculated.on_interface:1225             	- 2.1.18 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
08:43:42 - INFO   	| calculated.on_interface:1226             	- 2.1.18 - 检测图片序号为0，匹配度0.988，匹配位置为(233, 64)
08:43:43 - INFO   	| map.auto_map:435                         	- 2.1.18 - map_3-6_7用时[1;92m『1分24.3秒』[0m,总计:[1;92m『1小时0分36.0秒』[0m
08:43:43 - INFO   	| log.webhook_and_log:61                   	- 2.1.18 - [0;96;40m鳞渊境-1[0m
08:43:43 - INFO   	| map.auto_map:283                         	- 2.1.18 - 路线领航员：[1;95m喵不可言,龙女姬[0m 感谢她(们)的无私奉献，准备开始路线：map_3-7_1
08:43:43 - INFO   	| map.auto_map:289                         	- 2.1.18 - map
08:43:43 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:43:47 - INFO   	| map.map_init:49                          	- 2.1.18 - 识别点位(625, 986)
08:43:47 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\orientation_1.png
08:43:49 - INFO   	| calculated.click:138                     	- 2.1.18 - 点击坐标(1641, 139)，坐标来源图片匹配度1.000
08:43:49 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（1）
08:43:49 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\orientation_4.png
08:43:50 - INFO   	| calculated.have_screenshot:271           	- 2.1.18 - 找到图片，匹配值：0.983
08:43:50 - INFO   	| calculated.click:138                     	- 2.1.18 - 点击坐标(967, 809)，坐标来源图片匹配度0.982
08:43:52 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（2）
08:43:52 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\map_3-7.png
08:43:54 - INFO   	| calculated.click:138                     	- 2.1.18 - 点击坐标(1515, 936)，坐标来源图片匹配度1.000
08:43:54 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（3）
08:43:54 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\map_3-7_point_1.png
08:44:26 - INFO   	| calculated.click_target:433              	- 2.1.18 - 查找图片超时 picture\map_3-7_point_1.png ，最相似图片匹配值 0.8459993004798889，所需匹配值 0.93
08:44:26 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（4）
08:44:26 - INFO   	| log.webhook_and_log:61                   	- 2.1.18 - [0;96;40m鳞渊境-1[0m
08:44:26 - INFO   	| map.auto_map:283                         	- 2.1.18 - 路线领航员：[1;95m喵不可言,龙女姬[0m 感谢她(们)的无私奉献，准备开始路线：map_3-7_1
08:44:26 - INFO   	| map.auto_map:289                         	- 2.1.18 - map
08:44:26 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:44:29 - INFO   	| calculated.on_interface:1225             	- 2.1.18 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
08:44:29 - INFO   	| calculated.on_interface:1226             	- 2.1.18 - 检测图片序号为0，匹配度0.988，匹配位置为(233, 64)
08:44:29 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:44:32 - INFO   	| map.map_init:49                          	- 2.1.18 - 识别点位(625, 986)
08:44:32 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\orientation_1.png
08:44:34 - INFO   	| calculated.click:138                     	- 2.1.18 - 点击坐标(1641, 139)，坐标来源图片匹配度1.000
08:44:34 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（5）
08:44:34 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\orientation_4.png
08:44:35 - INFO   	| calculated.have_screenshot:271           	- 2.1.18 - 找到图片，匹配值：0.982
08:44:35 - INFO   	| calculated.click:138                     	- 2.1.18 - 点击坐标(967, 809)，坐标来源图片匹配度0.982
08:44:37 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（6）
08:44:37 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\map_3-7.png
08:44:39 - INFO   	| calculated.click:138                     	- 2.1.18 - 点击坐标(1515, 936)，坐标来源图片匹配度1.000
08:44:39 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（7）
08:44:39 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\map_3-7_point_1.png
08:45:11 - INFO   	| calculated.click_target:433              	- 2.1.18 - 查找图片超时 picture\map_3-7_point_1.png ，最相似图片匹配值 0.8459993004798889，所需匹配值 0.93
08:45:11 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（8）
08:45:11 - INFO   	| log.webhook_and_log:61                   	- 2.1.18 - [0;96;40m鳞渊境-2[0m
08:45:11 - INFO   	| map.auto_map:283                         	- 2.1.18 - 路线领航员：[1;95m喵不可言,龙女姬[0m 感谢她(们)的无私奉献，准备开始路线：map_3-7_2
08:45:11 - INFO   	| map.auto_map:289                         	- 2.1.18 - map
08:45:11 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:45:14 - INFO   	| calculated.on_interface:1225             	- 2.1.18 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
08:45:14 - INFO   	| calculated.on_interface:1226             	- 2.1.18 - 检测图片序号为0，匹配度0.988，匹配位置为(233, 64)
08:45:14 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:45:18 - INFO   	| map.map_init:49                          	- 2.1.18 - 识别点位(625, 986)
08:45:18 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\map_3-7_point_2.png
08:45:19 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向下移动，当前所需匹配值0.975
08:45:24 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向左移动，当前所需匹配值0.975
08:45:30 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向上移动，当前所需匹配值0.975
08:45:35 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向右移动，当前所需匹配值0.975
08:45:41 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向下移动，当前所需匹配值0.965
08:45:46 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向左移动，当前所需匹配值0.965
08:45:51 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向上移动，当前所需匹配值0.965
08:45:57 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向右移动，当前所需匹配值0.965
08:46:02 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向下移动，当前所需匹配值0.955
08:46:08 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向左移动，当前所需匹配值0.955
08:46:13 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向上移动，当前所需匹配值0.955
08:46:19 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向右移动，当前所需匹配值0.955
08:46:55 - INFO   	| calculated.click_target:433              	- 2.1.18 - 查找图片超时 picture\map_3-7_point_2.png ，最相似图片匹配值 0.8660281300544739，所需匹配值 0.93
08:46:55 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（1）
08:46:55 - INFO   	| log.webhook_and_log:61                   	- 2.1.18 - [0;96;40m鳞渊境-2[0m
08:46:55 - INFO   	| map.auto_map:283                         	- 2.1.18 - 路线领航员：[1;95m喵不可言,龙女姬[0m 感谢她(们)的无私奉献，准备开始路线：map_3-7_2
08:46:55 - INFO   	| map.auto_map:289                         	- 2.1.18 - map
08:46:55 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:46:59 - INFO   	| calculated.on_interface:1225             	- 2.1.18 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
08:46:59 - INFO   	| calculated.on_interface:1226             	- 2.1.18 - 检测图片序号为0，匹配度0.988，匹配位置为(233, 64)
08:46:59 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:47:02 - INFO   	| map.map_init:49                          	- 2.1.18 - 识别点位(625, 986)
08:47:02 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\map_3-7_point_2.png
08:47:03 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向下移动，当前所需匹配值0.975
08:47:09 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向左移动，当前所需匹配值0.975
08:47:14 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向上移动，当前所需匹配值0.975
08:47:19 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向右移动，当前所需匹配值0.975
08:47:25 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向下移动，当前所需匹配值0.965
08:47:31 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向左移动，当前所需匹配值0.965
08:47:36 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向上移动，当前所需匹配值0.965
08:47:41 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向右移动，当前所需匹配值0.965
08:47:47 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向下移动，当前所需匹配值0.955
08:47:52 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向左移动，当前所需匹配值0.955
08:47:58 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向上移动，当前所需匹配值0.955
08:48:03 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向右移动，当前所需匹配值0.955
08:48:40 - INFO   	| calculated.click_target:433              	- 2.1.18 - 查找图片超时 picture\map_3-7_point_2.png ，最相似图片匹配值 0.8660282492637634，所需匹配值 0.93
08:48:40 - INFO   	| map.auto_map:408                         	- 2.1.18 - 传送点击（2）
08:48:40 - INFO   	| log.webhook_and_log:61                   	- 2.1.18 - [0;96;40m鳞渊境-3[0m
08:48:40 - INFO   	| map.auto_map:283                         	- 2.1.18 - 路线领航员：[1;95m喵不可言,龙女姬[0m 感谢她(们)的无私奉献，准备开始路线：map_3-7_3
08:48:40 - INFO   	| map.auto_map:289                         	- 2.1.18 - map
08:48:40 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:48:44 - INFO   	| calculated.on_interface:1225             	- 2.1.18 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
08:48:44 - INFO   	| calculated.on_interface:1226             	- 2.1.18 - 检测图片序号为0，匹配度0.988，匹配位置为(233, 64)
08:48:44 - INFO   	| map.map_init:37                          	- 2.1.18 - 打开地图
08:48:47 - INFO   	| map.map_init:49                          	- 2.1.18 - 识别点位(625, 986)
08:48:47 - INFO   	| map.auto_map:289                         	- 2.1.18 - picture\map_3-7_point_3.png
08:48:48 - INFO   	| map.find_transfer_point:183              	- 2.1.18 - 开始移动地图，向下移动，当前所需匹配值0.975
08:48:48 - ERROR  	| fhoe.<module>:334                        	- 2.1.18 - Traceback (most recent call last):
  File "fhoe.py", line 325, in <module>
  File "fhoe.py", line 151, in main
  File "utils\map.py", line 399, in auto_map
  File "utils\map.py", line 186, in find_transfer_point
  File "utils\calculated.py", line 182, in mouse_drag
  File "utils\calculated.py", line 120, in get_rect
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')
```

**Comment by smjes3** [comment]
避免顶号即可，顶号情况暂时不会做出处理。
