### ISSUE TITLE
最后一张图4-7-9的这里出了问题

### ISSUE THREAD

**Issue by xibaibai9527** [linruowuyin/Fhoe-Rail#303]
### 问题描述

![无标题](https://github.com/linruowuyin/Fhoe-Rail/assets/19858971/927cd450-a69f-4302-b398-84e30ea19306)

位置是在这里，角色站的位置，在路中央有个气球，角色没打气球，导致后续一系列行动全撞在气球上了。

另外不知道是不是bug，今天刚更新2.2.17版本，挂在后台（自我远程连接），过了几个小时后回来发现游戏白屏卡死了，位置是4-7-8  3d地图进门的门口（未进门），日志在下面

### 日志

16:08:15 - INFO   	| calculated.on_interface:1366             	- 2.2.17 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.858
16:08:16 - INFO   	| calculated.on_interface:1366             	- 2.2.17 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.833
16:08:18 - INFO   	| calculated.on_interface:1366             	- 2.2.17 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.858
16:08:19 - INFO   	| calculated.on_interface:1366             	- 2.2.17 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.833
16:08:21 - INFO   	| calculated.on_interface:1366             	- 2.2.17 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.858
16:08:21 - INFO   	| calculated.on_interface:1366             	- 2.2.17 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.833
16:08:22 - ERROR  	| fhoe.<module>:358                        	- 2.2.17 - Traceback (most recent call last):
  File "fhoe.py", line 349, in <module>
  File "fhoe.py", line 151, in main
  File "utils\map.py", line 492, in auto_map
  File "utils\calculated.py", line 846, in auto_map
  File "utils\calculated.py", line 961, in handle_main
  File "utils\calculated.py", line 1309, in back_to_main
  File "utils\calculated.py", line 1333, in on_main_interface
  File "utils\calculated.py", line 1354, in on_interface
  File "utils\calculated.py", line 342, in scan_screenshot
  File "utils\calculated.py", line 323, in take_screenshot
  File "PIL\ImageGrab.py", line 48, in grab
OSError: screen grab failed

**Comment by smjes3** [comment]
1、报错是因为游戏白屏卡死导致的程序截图失败的报错，非程序问题
2、4-7-9的是黄泉的还是远程跑图的？

**Comment by xibaibai9527** [comment]
4-7-9的气球挡路是黄泉

另外今天又遇到4-7-8同样的卡死了，不过这次我看到问题了：
![无标题](https://github.com/linruowuyin/Fhoe-Rail/assets/19858971/8c674e91-29bc-4166-8d98-d234986d297f)

点击移动桥梁后，无任何反映，F按钮也消失了
不是掉线，等了好几分钟也没反应
再看了一眼昨天的日志，一模一样，都是在   执行map_4-7_8文件:51/81 
然后日志后面就没了

我把昨天和今天的日志传上来了
[logs.zip](https://github.com/user-attachments/files/15509527/logs.zip)
