### ISSUE TITLE
锄大地失败，基本锄几张图就跳，最新版本

### ISSUE THREAD

**Issue by i-cecreamer** [linruowuyin/Fhoe-Rail#51]
3:14:09 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_3-7_5文件:3/8 {'w': 1.08}
23:14:10 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_3-7_5文件:4/8 {'a': 5.8}
23:14:15 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_3-7_5文件:5/8 {'fighting': 1}
23:14:15 - INFO	| calculated.fighting:197 - 3.1 -  识别中
23:14:23 - INFO	| calculated.fighting:244 - 3.1 -  开启自动战斗
23:14:25 - INFO	| calculated.fighting:244 - 3.1 -  开启自动战斗
23:14:57 - ERROR	| Honkai_Star_Rail.<module>:138 - 3.1 -  Traceback (most recent call last):
  File "Honkai_Star_Rail.py", line 130, in <module>
  File "Honkai_Star_Rail.py", line 80, in main
  File "utils\map.py", line 136, in auto_map
  File "utils\calculated.py", line 415, in auto_map
  File "utils\calculated.py", line 223, in fighting
  File "utils\calculated.py", line 130, in scan_screenshot
  File "utils\calculated.py", line 103, in take_screenshot
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

**Comment by i-cecreamer** [comment]
9:53 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:43/63 {'d': 1.313}
00:59:55 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:44/63 {'s': 1.0318}
00:59:56 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:45/63 {'d': 1.776}
00:59:58 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:46/63 {'w': 0.032}
00:59:58 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:47/63 {'d': 0.9}
00:59:59 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:48/63 {'w': 0.782}
00:59:59 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:49/63 {'d': 0.9375}
01:00:00 - INFO	| calculated.auto_map:386 - 3.1 -  执行map_4-1_2文件:50/63 {'fighting': 1}
01:00:00 - INFO	| calculated.fighting:197 - 3.1 -  识别中
01:00:07 - ERROR	| Honkai_Star_Rail.<module>:138 - 3.1 -  Traceback (most recent call last):
  File "Honkai_Star_Rail.py", line 130, in <module>
  File "Honkai_Star_Rail.py", line 80, in main
  File "utils\map.py", line 136, in auto_map
  File "utils\calculated.py", line 415, in auto_map
  File "utils\calculated.py", line 223, in fighting
  File "utils\calculated.py", line 130, in scan_screenshot
  File "utils\calculated.py", line 103, in take_screenshot
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

**Comment by linruowuyin** [comment]
不知道啊，旧版没问题？

**Comment by smjes3** [comment]
@i-cecreamer 2.059是否还会出现该问题？

**Comment by i-cecreamer** [comment]
> @i-cecreamer 2.059是否还会出现该问题？

目前是2月27更新的版本，不知道是啥版本号，这两天正常运行

**Comment by smjes3** [comment]
已有其他日志表明是游戏闪退问题，之后看情况做一个闪退后等待一段时间自动打开游戏自动登录的版本。
目前游戏闪退概率较低，优先级不高。
